test:
  image: golang:latest
  before_script:
    - apt-get update && apt-get install -y protobuf-compiler
    - go mod download
    - go install github.com/golang/protobuf/proto
    - go install github.com/golang/protobuf/protoc-gen-go
    - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
    - go generate ./...
  script:
    - find plugins -type d -mindepth 1 -maxdepth 1 -exec sh -c 'cd ./{} && go build .' \;
    - go test -v -cover ./...

test-dind:
  image: golang:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - apt-get update && apt-get install -y protobuf-compiler docker.io
    - go mod download
    - go install github.com/golang/protobuf/proto
    - go install github.com/golang/protobuf/protoc-gen-go
    - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
    - go generate ./...
  script:
    - find plugins -type d -mindepth 1 -maxdepth 1 -exec sh -c 'cd ./{} && go build .' \;
    - go test -v -cover ./...

golangci-linter:
  image:
    name: golangci/golangci-lint:latest
    entrypoint: [""]
  allow_failure: true
  before_script:
    - apt-get update && apt-get install -y protobuf-compiler
    - go mod download
    - go install github.com/golang/protobuf/proto
    - go install github.com/golang/protobuf/protoc-gen-go
    - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
    - go generate ./...
  script:
    - golangci-lint run --timeout 1h ./...

build:
  image: golang:latest
  before_script:
    - apt-get update && apt-get install -y protobuf-compiler
    - go mod download
    - go install github.com/golang/protobuf/proto
    - go install github.com/golang/protobuf/protoc-gen-go
    - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
    - go generate ./...
  script:
    - find cmd -type d -mindepth 1 -maxdepth 1 -exec go build ./{}/... \;
    - find plugins -type d -mindepth 1 -maxdepth 1 -exec sh -c 'cd ./{} && go build .' \;
  artifacts:
    untracked: true