debug: true
db: test.db
plugin:
  debug: true
  path:
    - ./built-plugins
  workdir: /tmp/go-cloud/
  namespaced: true
  network_mode: "host"
storage:
  provider: plugin:minio
  extra:
    hostname: '192.168.100.124:9000'
    https: false
    access_key: go-cloud
    secret_key: ThisIsASecret
    prefix: cloud-
