debug: true
db: test.db
plugin:
  debug: true
  path:
    - ./built-plugins
  workdir: /tmp/leicht-cloud/
  runtime: "namespace"
  options:
    network_mode: "userspace"
fileinfo:
  mime_provider: "gonative"
  providers:
    - md5
    - sha1
    - sha256
    - sha384
    - sha512
    - sha3-224
    - sha3-256
    - sha3-384
    - sha3-512
    - plugin:imagesize
storage:
  provider: local
  extra:
    path: /data/leicht-cloud
